version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
      time: "12:00"
      timezone: "Europe/Helsinki"
    open-pull-requests-limit: 10
    reviewers:
      - jerr0328
    commit-message:
      prefix: "⬆️"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
      time: "12:00"
      timezone: "Europe/Helsinki"
    open-pull-requests-limit: 10
    reviewers:
      - jerr0328
    commit-message:
      prefix: "⬆️"
